#!/bin/sh

USAGE='[OPTION]... ( FILE [--and FILE]... [--to FILE] )...'
DESCRIPTION='Convert Java code to Ceylon'
LONG_USAGE='    ceylon convert "full/directory/of/java/file.java" "test.ceylon"

OPTIONS

--help
    Print this help message.
    
--tranformGetters
	Transform getters to properties.'

. $CEYLON_HOME/bin/ceylon-sh-setup

$CEYLON run ceylon.tool.converter.java2ceylon/1.2.3.SNAPSHOT "$@"
